# Generated by Django 4.1.4 on 2022-12-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historic_animes',
            field=models.ManyToManyField(to='anime.anime'),
        ),
    ]
